packages:
  - apps/*
  - config/*
  - packages/*

catalog:
  "@eslint/js": ^9.38.0
  "@types/node": ^22.18.12
  eslint: ^9.38.0
  openapi-fetch: ^0.13.5
  openapi-typescript: ^7.6.1
  prettier: ^3.6.2
  tailwindcss: ^3.4.15
  tsdown: ^0.18.3
  typescript: ^5.9.3
  zod: ^4.1.12

onlyBuiltDependencies:
  - esbuild

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"